language: node_js
sudo: false
node_js:
  - '6.10.2'
addons:
  apt:
    postgresql: '9.6'
services:
  - postgresql
before_script:
  - createuser --createdb --login aapod_user
  - createdb --owner aapod_user aapod_local
  - yarn run db:migrate
script:
  - yarn test
after_script:
  - yarn run enforce
