'use strict';

module.exports = {
  APOD_API_KEY: process.env.APOD_API_KEY,
  AWS_ACCESS_KEY_ID: process.env.AWS_ACCESS_KEY_ID,
  AWS_ASSET_BUCKET: process.env.AWS_ASSET_BUCKET,
  AWS_SECRET_ACCESS_KEY: process.env.AWS_SECRET_ACCESS_KEY,
  DATABASE_DATABASE: process.env.DATABASE_DATABASE,
  DATABASE_HOST: process.env.DATABASE_HOST,
  DATABASE_PASSWORD: process.env.DATABASE_PASSWORD,
  DATABASE_PORT: process.env.PORT,
  DATABASE_USER: process.env.DATABASE_USER,
  PORT: process.env.PORT
}
